shop_app_homepage:
    path:     /
    defaults: { _controller: ShopAppBundle:Index:index }

_add_product:
    defaults: { _controller: ShopAppBundle:Index:addProduct }
    path:     /add-product

_order_product:
    defaults: { _controller: ShopAppBundle:Index:orderProduct }
    path:     /order-product

_show_order:
    defaults: { _controller: ShopAppBundle:Index:show }
    path:     /show-order

_edit_product:
    defaults: { _controller: ShopAppBundle:Index:edit }
    path:     /edit-product

_edit_order:
    defaults: { _controller: ShopAppBundle:Index:edit }
    path:     /edit-order